# Generated by Django 5.2.8 on 2025-11-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='inn',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
