# Generated by Django 5.2.8 on 2025-11-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_inn_alter_partner_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='type',
            new_name='partner_type',
        ),
    ]
